#
# Automatically generated by blueprint(7).  Edit at your own risk.
#
class digitaloceanubuntulamp {
	Exec {
		path => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games',
	}
	Class['sources'] -> Class['files'] -> Class['packages']
	class files {
		file {
			'/etc':
				ensure => directory;
			'/etc/apache2':
				ensure => directory;
			'/etc/apache2/conf-enabled':
				ensure => directory;
			'/etc/apache2/conf-enabled/other-vhosts-access-log.conf':
				ensure => '../conf-available/other-vhosts-access-log.conf',
				group  => root,
				owner  => root;
			'/etc/apt':
				ensure => directory;
			'/etc/apt/sources.list':
				content => template('digitaloceanubuntulamp/etc/apt/sources.list'),
				ensure  => file,
				group   => root,
				mode    => 0644,
				owner   => root;
			'/etc/apt/trusted.gpg.d':
				ensure => directory;
			'/etc/apt/trusted.gpg.d/devstructure.gpg':
				content => template('digitaloceanubuntulamp/etc/apt/trusted.gpg.d/devstructure.gpg'),
				ensure  => file,
				group   => root,
				mode    => 0644,
				owner   => root;
			'/etc/blueprintignore':
				content => template('digitaloceanubuntulamp/etc/blueprintignore'),
				ensure  => file,
				group   => root,
				mode    => 0644,
				owner   => root;
			'/etc/motd.tail':
				content => template('digitaloceanubuntulamp/etc/motd.tail'),
				ensure  => file,
				group   => root,
				mode    => 0644,
				owner   => root;
			'/etc/php5':
				ensure => directory;
			'/etc/php5/apache2':
				ensure => directory;
			'/etc/php5/apache2/php.ini':
				content => template('digitaloceanubuntulamp/etc/php5/apache2/php.ini'),
				ensure  => file,
				group   => root,
				mode    => 0644,
				owner   => root;
			'/etc/php5/cli':
				ensure => directory;
			'/etc/php5/cli/php.ini':
				content => template('digitaloceanubuntulamp/etc/php5/cli/php.ini'),
				ensure  => file,
				group   => root,
				mode    => 0644,
				owner   => root;
			'/etc/ssh':
				ensure => directory;
			'/etc/ssh/sshd_config':
				content => template('digitaloceanubuntulamp/etc/ssh/sshd_config'),
				ensure  => file,
				group   => root,
				mode    => 0644,
				owner   => root;
		}
	}
	include files
	class packages {
		exec { 'apt-get -q update':
			before => Class['apt'],
		}
		class apt {
			package {
				'arping':
					ensure => installed;
				'biosdevname':
					ensure => installed;
				'byobu':
					ensure => installed;
				'curl':
					ensure => installed;
				'e2fslibs:amd64':
					ensure => installed;
				'ethtool':
					ensure => installed;
				'fonts-ubuntu-font-family-console':
					ensure => installed;
				'gawk':
					ensure => installed;
				'gcc-4.8-base:amd64':
					ensure => installed;
				'gcc-4.9-base:amd64':
					ensure => installed;
				'git':
					ensure => installed;
				'git-core':
					ensure => installed;
				'git-man':
					ensure => installed;
				'libaccountsservice0:amd64':
					ensure => installed;
				'libacl1:amd64':
					ensure => installed;
				'libaio1:amd64':
					ensure => installed;
				'libapache2-mod-auth-mysql':
					ensure => installed;
				'libapparmor1:amd64':
					ensure => installed;
				'libapr1:amd64':
					ensure => installed;
				'libaprutil1-dbd-sqlite3:amd64':
					ensure => installed;
				'libaprutil1-ldap:amd64':
					ensure => installed;
				'libaprutil1:amd64':
					ensure => installed;
				'libapt-inst1.5:amd64':
					ensure => installed;
				'libapt-pkg4.12:amd64':
					ensure => installed;
				'libasn1-8-heimdal:amd64':
					ensure => installed;
				'libasprintf0c2:amd64':
					ensure => installed;
				'libattr1:amd64':
					ensure => installed;
				'libaudit1:amd64':
					ensure => installed;
				'libblkid1:amd64':
					ensure => installed;
				'libboost-iostreams1.54.0:amd64':
					ensure => installed;
				'libbsd0:amd64':
					ensure => installed;
				'libbz2-1.0:amd64':
					ensure => installed;
				'libc-ares2:amd64':
					ensure => installed;
				'libc6:amd64':
					ensure => installed;
				'libcap2:amd64':
					ensure => installed;
				'libcgmanager0:amd64':
					ensure => installed;
				'libck-connector0:amd64':
					ensure => installed;
				'libcloog-isl4:amd64':
					ensure => installed;
				'libcomerr2:amd64':
					ensure => installed;
				'libcurl3-gnutls:amd64':
					ensure => installed;
				'libcurl3:amd64':
					ensure => installed;
				'libdb5.3:amd64':
					ensure => installed;
				'libdbus-1-3:amd64':
					ensure => installed;
				'libdbus-glib-1-2:amd64':
					ensure => installed;
				'libdebconfclient0:amd64':
					ensure => installed;
				'libdevmapper1.02.1:amd64':
					ensure => installed;
				'libdrm2:amd64':
					ensure => installed;
				'libedit2:amd64':
					ensure => installed;
				'libelf1:amd64':
					ensure => installed;
				'libept1.4.12:amd64':
					ensure => installed;
				'liberror-perl':
					ensure => installed;
				'libevent-2.0-5:amd64':
					ensure => installed;
				'libexpat1:amd64':
					ensure => installed;
				'libffi6:amd64':
					ensure => installed;
				'libfontconfig1:amd64':
					ensure => installed;
				'libfreetype6:amd64':
					ensure => installed;
				'libfribidi0:amd64':
					ensure => installed;
				'libfuse2:amd64':
					ensure => installed;
				'libgc1c2:amd64':
					ensure => installed;
				'libgcc1:amd64':
					ensure => installed;
				'libgck-1-0:amd64':
					ensure => installed;
				'libgcr-base-3-1:amd64':
					ensure => installed;
				'libgcrypt11:amd64':
					ensure => installed;
				'libgd3:amd64':
					ensure => installed;
				'libgdbm3:amd64':
					ensure => installed;
				'libgeoip1:amd64':
					ensure => installed;
				'libglib2.0-0:amd64':
					ensure => installed;
				'libgmp10:amd64':
					ensure => installed;
				'libgnutls-openssl27:amd64':
					ensure => installed;
				'libgnutls26:amd64':
					ensure => installed;
				'libgpg-error0:amd64':
					ensure => installed;
				'libgpm2:amd64':
					ensure => installed;
				'libgssapi-krb5-2:amd64':
					ensure => installed;
				'libgssapi3-heimdal:amd64':
					ensure => installed;
				'libhcrypto4-heimdal:amd64':
					ensure => installed;
				'libheimbase1-heimdal:amd64':
					ensure => installed;
				'libheimntlm0-heimdal:amd64':
					ensure => installed;
				'libhx509-5-heimdal:amd64':
					ensure => installed;
				'libidn11:amd64':
					ensure => installed;
				'libisl10:amd64':
					ensure => installed;
				'libiw30:amd64':
					ensure => installed;
				'libjbig0:amd64':
					ensure => installed;
				'libjpeg-turbo8:amd64':
					ensure => installed;
				'libjpeg8:amd64':
					ensure => installed;
				'libjson-c2:amd64':
					ensure => installed;
				'libjson0:amd64':
					ensure => installed;
				'libk5crypto3:amd64':
					ensure => installed;
				'libkeyutils1:amd64':
					ensure => installed;
				'libkmod2:amd64':
					ensure => installed;
				'libkrb5-26-heimdal:amd64':
					ensure => installed;
				'libkrb5-3:amd64':
					ensure => installed;
				'libkrb5support0:amd64':
					ensure => installed;
				'libldap-2.4-2:amd64':
					ensure => installed;
				'liblockfile1:amd64':
					ensure => installed;
				'liblua5.2-0:amd64':
					ensure => installed;
				'liblzma5:amd64':
					ensure => installed;
				'libmagic1:amd64':
					ensure => installed;
				'libmcrypt4':
					ensure => installed;
				'libmount1:amd64':
					ensure => installed;
				'libmpc3:amd64':
					ensure => installed;
				'libmpdec2:amd64':
					ensure => installed;
				'libmpfr4:amd64':
					ensure => installed;
				'libmysqlclient18:amd64':
					ensure => installed;
				'libncurses5:amd64':
					ensure => installed;
				'libncursesw5:amd64':
					ensure => installed;
				'libnet1:amd64':
					ensure => installed;
				'libnewt0.52:amd64':
					ensure => installed;
				'libnfnetlink0:amd64':
					ensure => installed;
				'libnih-dbus1:amd64':
					ensure => installed;
				'libnih1:amd64':
					ensure => installed;
				'libnl-3-200:amd64':
					ensure => installed;
				'libnl-genl-3-200:amd64':
					ensure => installed;
				'libnuma1:amd64':
					ensure => installed;
				'libp11-kit0:amd64':
					ensure => installed;
				'libpam-cap:amd64':
					ensure => installed;
				'libpam-modules:amd64':
					ensure => installed;
				'libpam-systemd:amd64':
					ensure => installed;
				'libpam0g:amd64':
					ensure => installed;
				'libparted0debian1:amd64':
					ensure => installed;
				'libpcap0.8:amd64':
					ensure => installed;
				'libpci3:amd64':
					ensure => installed;
				'libpcre3:amd64':
					ensure => installed;
				'libpcsclite1:amd64':
					ensure => installed;
				'libpipeline1:amd64':
					ensure => installed;
				'libplymouth2:amd64':
					ensure => installed;
				'libpng12-0:amd64':
					ensure => installed;
				'libpolkit-agent-1-0:amd64':
					ensure => installed;
				'libpolkit-backend-1-0:amd64':
					ensure => installed;
				'libpolkit-gobject-1-0:amd64':
					ensure => installed;
				'libpopt0:amd64':
					ensure => installed;
				'libprocps3:amd64':
					ensure => installed;
				'libpython-stdlib:amd64':
					ensure => installed;
				'libpython2.7-minimal:amd64':
					ensure => installed;
				'libpython2.7-stdlib:amd64':
					ensure => installed;
				'libpython2.7:amd64':
					ensure => installed;
				'libpython3-stdlib:amd64':
					ensure => installed;
				'libpython3.4-minimal:amd64':
					ensure => installed;
				'libpython3.4-stdlib:amd64':
					ensure => installed;
				'libreadline5:amd64':
					ensure => installed;
				'libreadline6:amd64':
					ensure => installed;
				'libroken18-heimdal:amd64':
					ensure => installed;
				'librtmp0:amd64':
					ensure => installed;
				'libsasl2-2:amd64':
					ensure => installed;
				'libsasl2-modules-db:amd64':
					ensure => installed;
				'libsasl2-modules:amd64':
					ensure => installed;
				'libselinux1:amd64':
					ensure => installed;
				'libsemanage1:amd64':
					ensure => installed;
				'libsepol1:amd64':
					ensure => installed;
				'libsigc++-2.0-0c2a:amd64':
					ensure => installed;
				'libsigsegv2:amd64':
					ensure => installed;
				'libslang2:amd64':
					ensure => installed;
				'libsmi2ldbl:amd64':
					ensure => installed;
				'libsqlite3-0:amd64':
					ensure => installed;
				'libss2:amd64':
					ensure => installed;
				'libssl1.0.0:amd64':
					ensure => installed;
				'libstdc++6:amd64':
					ensure => installed;
				'libsystemd-daemon0:amd64':
					ensure => installed;
				'libsystemd-login0:amd64':
					ensure => installed;
				'libtasn1-6:amd64':
					ensure => installed;
				'libtiff5:amd64':
					ensure => installed;
				'libtinfo5:amd64':
					ensure => installed;
				'libudev1:amd64':
					ensure => installed;
				'libusb-0.1-4:amd64':
					ensure => installed;
				'libusb-1.0-0:amd64':
					ensure => installed;
				'libustr-1.0-1:amd64':
					ensure => installed;
				'libuuid1:amd64':
					ensure => installed;
				'libvpx1:amd64':
					ensure => installed;
				'libwind0-heimdal:amd64':
					ensure => installed;
				'libwireshark3:amd64':
					ensure => installed;
				'libwiretap3:amd64':
					ensure => installed;
				'libwrap0:amd64':
					ensure => installed;
				'libwsutil3:amd64':
					ensure => installed;
				'libx11-6:amd64':
					ensure => installed;
				'libxau6:amd64':
					ensure => installed;
				'libxcb1:amd64':
					ensure => installed;
				'libxdmcp6:amd64':
					ensure => installed;
				'libxext6:amd64':
					ensure => installed;
				'libxml2:amd64':
					ensure => installed;
				'libxmuu1:amd64':
					ensure => installed;
				'libxpm4:amd64':
					ensure => installed;
				'linux-headers-3.13.0-24':
					ensure => installed;
				'linux-headers-3.13.0-24-generic':
					ensure => installed;
				'linux-image-3.13.0-24-generic':
					ensure => installed;
				'linux-image-extra-3.13.0-24-generic':
					ensure => installed;
				'memtest86+':
					ensure => installed;
				'mysql-server':
					ensure => installed;
				'openssh-server':
					ensure => installed;
				'openssh-sftp-server':
					ensure => installed;
				'php5':
					ensure => installed;
				'php5-gd':
					ensure => installed;
				'php5-mcrypt':
					ensure => installed;
				'php5-mysql':
					ensure => installed;
				'python3-gdbm:amd64':
					ensure => installed;
				'python3-newt':
					ensure => installed;
				'python3-pycurl':
					ensure => installed;
				'python3-software-properties':
					ensure => installed;
				'run-one':
					ensure => installed;
				'screen':
					ensure => installed;
				'software-properties-common':
					ensure => installed;
				'tmux':
					ensure => installed;
				'unattended-upgrades':
					ensure => installed;
				'wireless-tools':
					ensure => installed;
				'wpasupplicant':
					ensure => installed;
				'zlib1g:amd64':
					ensure => installed;
			}
		}
		include apt
	}
	include packages
	class sources {
		exec { 'tar xf /tmp/99628065e99358ccf4e37e3c463d42ef47604b07.tar':
			alias => '/usr/local',
			cwd   => '/usr/local',
		}
		file { '/tmp/99628065e99358ccf4e37e3c463d42ef47604b07.tar':
			before => Exec['/usr/local'],
			group  => root,
			mode   => 0644,
			owner  => root,
			source => 'puppet:///modules/digitaloceanubuntulamp/tmp/99628065e99358ccf4e37e3c463d42ef47604b07.tar',
		}
	}
	include sources
}
